### ISSUE TITLE
need a way to add additional data to errors

### ISSUE THREAD

**Issue by daywiss** [soggie/jsonrpc-serializer#13]
You are adding additional data parameters to the error object with this call
```js
JsonRpcError = function JsonRpcError(msg) {
    this.name    = 'JsonRpcError';
    this.code    = -32603;
    this.message = msg;
    this.data    = Array.prototype.slice.call(arguments).splice();
};
```
The problem is that this.data always ends up with an empty array since calling splice with no arguments always returns [].  I'm not sure what you intended to do with the data parameter, but it would be nice if this could be fixed so that we can add additional data to the error such as the stack dump, etc. 

im currently using your library as a dependency in json-rpc-core. thanks!

**Comment by soggie** [comment]
It's such a long time since I revisited this library. Would you be open to integrating a new major version instead? I have a few additional features that I want to integrate, as well as upgrading the build tool to babel and ES6 compliant syntax, to mention a few changes.

**Comment by soggie** [comment]
I think it should be `.splice(1)` instead, so that you can input any number of arguments after it to get it included in the error.

**Comment by soggie** [comment]
New version pushed `v0.2.0` that has better exceptions. Adding a new functionality to customise your errors in `v0.2.1` soon.

**Comment by daywiss** [comment]
@soggie yes i can add a new major version. thanks for the update.
