### ISSUE TITLE
declare strict mode for older node versions

### ISSUE THREAD

**Issue by daywiss** [soggie/jsonrpc-serializer#14]
i just updated to version 0.2.0, but im getting an error when running. I think its because im using an older version of node: 4.6.2, but none the less i think you use need to use strict mode to fix this. 

```
/home/developer/src/json-rpc-core/node_modules/jsonrpc-serializer/lib/serializer.js:415
    let obj = null
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by soggie** [comment]
Fixed with v0.2.1.
