### ISSUE TITLE
It doesn't recognize "falsy" ids

### ISSUE THREAD

**Issue by vinipsmaker** [soggie/jsonrpc-serializer#9]
It's the same error all over every [JavaScript's JSON-RPC implementation](https://github.com/andris9/node-jsonrpc/issues/2).

Your implementation confuse requests and notifications if `id` is set to some _falsy_ value like `0` or `false`.

**Comment by soggie** [comment]
Sorry, I missed this comment. Will fix it as soon as I can!

**Comment by soggie** [comment]
@vinipsmaker I'm not sure if I understand this. According to the specification, you can use (1) Numbers, (2) Strings or (3) NULL.

Therefore, "falsy" values like 0 and "" (empty string) are actually allowed according to the JSONRPC specs, no?

**Comment by vinipsmaker** [comment]
> @vinipsmaker I'm not sure if I understand this. According to the specification, you can use (1) Numbers, (2) Strings or (3) NULL.

> Therefore, "falsy" values like 0 and "" (empty string) are actually allowed according to the JSONRPC specs, no?

They're allowed by the specification, but they don't work on your implementation.

**Comment by soggie** [comment]
Hi @vinipsmaker I tried the following sample code:

````
var ser = require('./lib/serializer');
console.log(ser.request(0, 'test', 'test'));
````

And the result is:

````
{"jsonrpc":"2.0","id":0,"method":"test","params":["test"]}
````

Also:

````
var ser = require('./lib/serializer');
console.log(ser.request('', 'test', 'test'));
````

And the result is:

````
{"jsonrpc":"2.0","id":"","method":"test","params":["test"]}
````

Can you give me a test code to illustrate how it doesn't work so I can fix it?

**Comment by vinipsmaker** [comment]
> Can you give me a test code to illustrate how it doesn't work so I can fix it?

Sure (and sorry about the delay):

```javascript
var jrs = require('jsonrpc-serializer');

// m.payload.id will be filled, as it should:
m=jrs.deserialize("{\"jsonrpc\":\"2.0\",\"method\":\"listFirst\",\"params\":[\"bta/0.1\"],\"id\":1}");

// m.type is mistaken as 'notification' and m.payload.id will be missing:
m=jrs.deserialize("{\"jsonrpc\":\"2.0\",\"method\":\"listFirst\",\"params\":[\"bta/0.1\"],\"id\":0}");
```
